export const sourceRegistry = [
  {
    id: "costco",
    name: "Costco",
    type: "official-retail",
    domain: "costco.com",
    priority: 10,
    categories: ["warehouse find", "savings / price drop", "seasonal item"],
  },
  {
    id: "walmart",
    name: "Walmart",
    type: "official-retail",
    domain: "walmart.com",
    priority: 10,
    categories: ["savings / price drop", "shopper alert", "new product / launch"],
  },
  {
    id: "target",
    name: "Target",
    type: "official-retail",
    domain: "target.com",
    priority: 10,
    categories: ["savings / price drop", "new product / launch", "seasonal item"],
  },
  {
    id: "sams-club",
    name: "Sam's Club",
    type: "official-retail",
    domain: "samsclub.com",
    priority: 10,
    categories: ["warehouse find", "clearance / ends soon", "hidden perk"],
  },
  {
    id: "fast-food",
    name: "Fast Food Promos",
    type: "official-restaurant",
    domain: "brand-owned",
    priority: 9,
    categories: ["fast food promo", "limited-time offer"],
  },
  {
    id: "recalls",
    name: "Recall Sources",
    type: "government",
    domain: "fda.gov / fsis.usda.gov / cpsc.gov",
    priority: 9,
    categories: ["recall / warning", "shopper alert"],
  },
  {
    id: "google-news",
    name: "Google News / Search",
    type: "discovery",
    domain: "news.google.com",
    priority: 7,
    categories: ["new product / launch", "shopper alert", "reopening"],
  },
  {
    id: "x-api",
    name: "Selected X Accounts",
    type: "social-api",
    domain: "x.com",
    priority: 6,
    categories: ["fast food promo", "deal alert", "launch"],
  },
];
